### ISSUE TITLE
Issue with velocities

### ISSUE THREAD

**Issue by wargnierq** [ITA-Solar/helita#28]
When considering get_var('ux',mf_species=1m;f_level=1), it is not consistent with get_var('px',mf_species=1m;f_level=1)/get_var('r',mf_species=1m;f_level=1). Sometimes I got an issue related to cstagger (in bifrost.py)

**Comment by tiagopereira** [comment]
The current version does not support `mf_species` or `f_level` keywords, so I assume this is related to Ebysus and belongs in https://github.com/jumasy/helita. You should ask @jumasy to open up issues on that fork and report it there. Closing for now, but can reopen if you can reproduce the bug also in pure bifrost output.
