### ISSUE TITLE
Numpy distutils is deprecated

### ISSUE THREAD

**Issue by meudnaes** [ITA-Solar/helita#49]
Installation of helita in Python 3.12 gives error on line https://github.com/ITA-Solar/helita/blob/39bf3033ce1b132f61205dffffb585c317087074/setup.py#L8

[numpy.distutils](https://numpy.org/doc/stable/reference/distutils.html#module-numpy.distutils) has been deprecated in NumPy 1.23.0 and is removed since Python 3.12

**Comment by tiagopereira** [comment]
Yes, this is a known issue. Right now it is not possible to install helita in python 3.12 because of the way the fortran and Cython modules are distributed. An alternative is to use [meson](https://docs.scipy.org/doc/scipy/building/understanding_meson.html) instead, but it does not seem trivial.

**Comment by tiagopereira** [comment]
Fixed by ef0255e.
